shortName=reminder
version=0.0.1
name=\u5F85\u529E\u63D0\u9192
author=xiaochun
indexPage=index
desc=\u57FA\u4E8E ZrLog \u90AE\u4EF6\u670D\u52A1\u7684\u4E2A\u4EBA\u4EE3\u529E\u4E0E\u5230\u671F\u63D0\u9192
paths=
dependentService=emailService
